# Generated by Django 5.0.3 on 2024-10-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highrise_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateslist',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='corporateslist',
            name='added_by',
            field=models.TextField(default='Admin', max_length=255),
        ),
    ]
