# Generated by Django 5.0.3 on 2024-09-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highrise_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpformdata',
            name='revisit',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='revisit',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='revisit',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
