# Generated by Django 5.0.3 on 2024-10-22 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highrise_app', '0001_initial'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='booking',
            name='EnquiryId',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='corporateslist',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 22, 11, 31, 42, 272930, tzinfo=datetime.timezone.utc)),
        ),
    ]
