# Generated by Django 5.0.3 on 2024-10-10 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highrise_app', '0002_alter_corporateslist_added_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateslist',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 10, 13, 0, 48, 428081, tzinfo=datetime.timezone.utc)),
        ),
    ]
