# Generated by Django 5.0.3 on 2024-10-23 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highrise_app', '0002_visit_type_source_alter_booking_enquiryid_and_more'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='booking',
            name='BookingDate',
            field=models.DateField(),
        ),
        
    ]
