# Generated by Django 5.0.3 on 2024-10-16 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highrise_app', '0003_alter_corporateslist_added_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit_Type_Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='corporateslist',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 6, 18, 21, 718390, tzinfo=datetime.timezone.utc)),
        ),
    ]
