# Generated by Django 5.0.3 on 2024-10-16 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highrise_app', '0003_alter_corporateslist_added_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientName', models.TextField(max_length=250)),
                ('ClientNumber', models.TextField(max_length=250)),
                ('EnquiryId', models.IntegerField()),
                ('EDate', models.DateTimeField()),
                ('HandledBY', models.TextField(max_length=250)),
                ('Project', models.TextField(max_length=255)),
                ('Unit', models.TextField(max_length=255)),
                ('StageChangeDate', models.DateTimeField()),
                ('Booking', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='corporateslist',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 11, 35, 48, 909318, tzinfo=datetime.timezone.utc)),
        ),
    ]
