# Generated by Django 5.0.3 on 2024-10-16 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highrise_app', '0004_booking_alter_corporateslist_added_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Booking',
            new_name='BookingDate',
        ),
        migrations.AlterField(
            model_name='corporateslist',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 11, 41, 21, 337802, tzinfo=datetime.timezone.utc)),
        ),
    ]
