# Generated by Django 5.0.3 on 2024-10-18 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highrise_app', '0005_rename_booking_booking_bookingdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='EnquiryId',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='corporateslist',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 18, 5, 30, 40, 384268, tzinfo=datetime.timezone.utc)),
        ),
    ]
